language: objective-c
compiler:
    - clang
branches:
    only:
        - master
notifications:
  recipients:
    - adobe-source-build@lists.sourceforge.net
  email:
    on_success: change
    on_failure: always
  slack: stlab:P23OMUJ8T4Pa05OON0VDYwIf
install:
    - ./configure.sh
env:
    - BUILDTOOL=bjam BUILDMODE=debug
    - BUILDTOOL=bjam BUILDMODE=release
script: ./build.sh
x
